name: Build docker image

env:
  PACKAGE_NAME: discord-bot
  PACKAGE_TAG: testing


run-name: ${{ github.actor }} is building the docker image

on:
  push:
    branches:
#      - 'test-**'
      - 'dev'

jobs:
    build_docker_image:
        runs-on: ubuntu-latest

        steps:
          - name: Checking out repository
            uses: actions/checkout@v4

          - name: Login to Goliath Container Registry
            uses: docker/login-action@v3
            with:
              registry: ${{ vars.PACKAGE_REPOSITORY }}
              username: ${{ secrets.PACKAGE_USER }}
              password: ${{ secrets.PACKAGE_PASS }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Create Docker Buildx contex
            run: docker buildx create --name goliath; docker buildx use goliath; docker buildx inspect --bootstrap;

          - name: Building docker image
            run: |
              docker buildx build . \
                --file build/default/Dockerfile \
                --platform linux/amd64,linux/arm64 \
                --tag ${{ vars.PACKAGE_REPOSITORY }}/${{ vars.PACKAGE_ORGANIZATION }}/${{ env.PACKAGE_NAME }}:${{ env.PACKAGE_TAG }} \
                --provenance=false \
                --sbom=false \
                --push
